import { Michroma } from "next/font/google";
import "./globals.css";
import Navbar from "./componads/nav/navbar";
import Footer from "./componads/footer/footer";
import Providers from "./providers";

const michroma = Michroma({
  weight: '400',
  subsets: ['latin'],
});


export const metadata = {
  title: "BOX MOVIE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navbar fontClass={michroma.className}/>
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
